---
# Main file for roles/windows/strawberry-perl
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook
# This is because |basename or filters in general don't work with galaxy

- name: Uninstall Strawberry Perl
  win_package:
    product_id: '{2DC518D0-750A-1014-A07D-5301D6FAD9F8}'
    state: absent

- name: Install Strawberry Perl
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/strawberry-perl/strawberry-perl-5.38.0.1-64bit.msi'
    state: present
    arguments: /qn /l*v "C:\logs\strawberry-perl-5.32.1.1-64bit.msi_install.log" TARGETDIR="D:\3rdparty\Strawberry" INSTALLDIR="D:\3rdparty\Strawberry" PERL_PATH=Yes
