---
# Main file for vmware-tools
# Generally speaking this shouldn't be changed at all, it should just work!

- name: install vmtools
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/vmtools/VMware-tools-12.3.5-22544099-x86_64.exe'
    state: present
    arguments: /S /v /qn REBOOT=R
  ignore_errors: True
