---
# Main file for roles/windows/SoapUI
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

- name: Install SoapUI
  win_package: 
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/soapui/SoapUI-x64-5.7.2.exe'
    state: present
    arguments: -q -overwrite -dir D:\3rdparty\SoapUI
