---
# Main file for roles/windows/vcredist 2013
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

- name: Install vcredist 2013
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/vcredist/vcredist_x64_2013.exe'
    state: present
    arguments: /q /norestart
