---
# Main file for roles/windows/winverifytrust fix
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

# Fix winverifytrust vuln
- name: Add wintrust config
  win_regedit:
    path: HKLM:\Software\Microsoft\Cryptography\Wintrust\Config
    name: EnableCertPaddingCheck
    data: 1
    type: string

- name: Add wintrust config WOW64
  win_regedit:
    path: HKLM:\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config
    name: EnableCertPaddingCheck
    data: 1
    type: string