---
# Main file for roles/windows/chrome
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

# Disable LM/NTLMv1 Authentication
- name: Add or update registry path Lsa, with dword entry 'lmcompatibilitylevel', and containing 5 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: lmcompatibilitylevel
    data: 5
    type: dword