---
# Main file for roles/windows/chrome
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

- name: Install chrome
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/chrome/googlechromestandaloneenterprise64.msi'
    state: present
    arguments: /qn
