---
# Main file for roles/windows/Amazon Coretto
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook
# This is because |basename or filters in general don't work with galaxy

#- name: Copy Amazon Coretto
#  win_copy:
#    src: '/opt/updates/amazon-corretto-11.0.21.9.1-windows-x64-jdk.zip'
#    dest: 'C:\\temp\\amazon-corretto-11.0.21.9.1-windows-x64-jdk.zip'

- name: Download Amazon Coretto
  win_get_url:
    url: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/amazon-coretto-jdk/amazon-corretto-11.0.21.9.1-windows-x64-jdk.zip'
    url_username: 'admin'
    url_password: 'MECO_Admin@2023'
    dest: 'C:\\temp\\amazon-corretto-11.0.21.9.1-windows-x64-jdk.zip'

- name: Create Coretto directory
  win_file:
    path: 'D:\\3rdparty\\Corretto'
    state: directory

- name: Unzip Amazon Coretto
  win_unzip:
    src: 'C:\\Temp\\amazon-corretto-11.0.21.9.1-windows-x64-jdk.zip'
    dest: 'D:\\3rdparty\\Corretto'
    #recurse: yes
    #delete_archive: yes

- name: Ensure that Amazon Coretto is present on the global system path, and in the specified order
  win_path:
    elements:
    - '"D:\3rdparty\Corretto\jdk11.0.21_9\bin"'
    - '"D:\3rdparty\Corretto\jdk11.0.21_9\bin\server"'

- name: Set JAVA_HOME environment variable for all users
  win_environment:
    state: present
    name: JAVA_HOME
    value: 'D:\3rdparty\Corretto\jdk11.0.21_9'
    level: machine

#- name: Unzip Amazon Coretto
  #unarchive:
    #src: 'C:\\temp\\amazon-corretto-11.0.21.9.1-windows-x64-jdk.zip'
    #dest: 'C:\\3rdparty\\Amazon Coretto\\'
#- name: Install Amazon Coretto
  #win_shell: 'C:\temp\amazon-corretto-11.0.21.9.1-windows-x64.msi /qn /l*v "C:\temp\amazon-corretto.log" TARGETDIR="D:\3rdparty\Amazon Coretto" INSTALLDIR="D:\3rdparty\Amazon Coretto"'
  #become: yes
  #become_method: runas
  #vars:
    #ansible_become_user: 'administrator'
    #ansible_become_pass: 'Passw0rd!'

#- name: Install Amazon Coretto
#  win_package:
#    path: 'C:\\temp\\amazon-corretto-11.0.21.9.1-windows-x64.msi'
#    state: present
#    arguments: /qn /l*v "C:\temp\amazon-corretto.log" TARGETDIR="D:\3rdparty\Amazon Coretto" INSTALLDIR="D:\3rdparty\Amazon Coretto"