---
# Main file for roles/windows/winverifytrust fix
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

# Fix winverifytrust vuln
- name: Add WUServer location
  win_regedit:
    path: HKLM:\Software\Microsoft\Policies\Microsoft\Windows\WindowsUpdate
    name: WUServer
    data: http://vwpcwp01mcc.ot.net:8530
    type: string

- name: Add WUStatusServer Location
  win_regedit:
    path: HKLM:\Software\Microsoft\Policies\Microsoft\Windows\WindowsUpdate
    name: WUStatusServer
    data: http://vwpcwp01mcc.ot.net:8530
    type: string

- name: Add WUStatusServer Location
  win_regedit:
    path: HKLM:\Software\Microsoft\Policies\Microsoft\Windows\WindowsUpdate
    name: TargetGroup
    data: full_updates
    type: string