---
# Main file for roles/windows/edge
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook
# This is because |basename or filters in general don't work with galaxy

- name: Install edge
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/edge/MicrosoftEdgeEnterpriseX64.msi'
    state: present
