---
# Main file for roles/windows/chrome
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

# Disable TLSv1.0 and TLSv1.1
- name: Add or update registry path TLS 1.0, with dword entry 'Enabled', and containing 0 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0
    name: Enabled
    data: 0
    type: dword

- name: Add or update registry path TLS 1.1, with dword entry 'Enabled', and containing 0 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1
    name: Enabled
    data: 0
    type: dword

- name: Add or update registry path TLS 1.0, with dword entry 'Enabled', and containing 0 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
    name: Enabled
    data: 0
    type: dword

- name: Add or update registry path TLS 1.0, with dword entry 'Enabled', and containing 0 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
    name: Enabled
    data: 0
    type: dword

- name: Add or update registry path TLS 1.0, with dword entry 'DisabledByDefault', and containing 1 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
    name: DisabledByDefault
    data: 1
    type: dword

- name: Add or update registry path TLS 1.0, with dword entry 'DisabledByDefault', and containing 1 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
    name: DisabledByDefault
    data: 1
    type: dword

- name: Add or update registry path TLS 1.1, with dword entry 'Enabled', and containing 0 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
    name: Enabled
    data: 0
    type: dword

- name: Add or update registry path TLS 1.1, with dword entry 'Enabled', and containing 0 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
    name: Enabled
    data: 0
    type: dword

- name: Add or update registry path TLS 1.1, with dword entry 'DisabledByDefault', and containing 1 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
    name: DisabledByDefault
    data: 1
    type: dword

- name: Add or update registry path TLS 1.1, with dword entry 'DisabledByDefault', and containing 1 as the decimal value
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
    name: DisabledByDefault
    data: 1
    type: dword