---
# Main file for roles/windows/notepad++
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

# - name: Copy notepad++
#   win_copy:
#     src: '/opt/updates/npp.8.6.Installer.x64.exe'
#     dest: 'C:\temp\npp.8.6.Installer.x64.exe'

#- name: Install notepad++
  #win_shell: 'C:\Temp\npp.8.6.Installer.x64.exe /S /D=C:\3rdparty\notepad++'

- name: Install notepad++
  win_package: 
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/notepad%2B%2B/npp.8.6.Installer.x64.exe'
    state: present
    arguments: /S /D=D:\3rdparty\Notepad++

- name: Ensure that notepad++ is present on the global system path, and in the specified order
  win_path:
    elements:
    - 'D:\3rdparty\notepad++'

- name: Copy notepad++ to notepp
  win_copy:
    src: 'D:\3rdparty\notepad++\notepad++.exe'
    dest: 'D:\3rdparty\notepad++\notepp.exe'
    remote_src: true

- name: Remove old notepad++ installation
  ansible.windows.win_file:
    path: 'C:\\Program Files\\Notepad++'
    state: absent
  ignore_errors: true
