---
# Main file for roles/windows/change-dir-owner
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

# Change directory owner
- name: Set the owner of root directory
  ansible.windows.win_owner:
    path: C:\Windows\System32
    user: Administrators
    recurse: false

- name: Set the correct permission for C:\WIndows\System32
  ansible.windows.win_acl:
    path: C:\Windows\System32
    user: Administrators
    type: allow
    rights: FullControl

- name: Set the correct permission for C:\WIndows\System32\curl.exe
  ansible.windows.win_acl:
    path: C:\Windows\System32\curl.exe
    user: Administrators
    type: allow
    rights: FullControl