---
# Main file for roles/windows/net-framework
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

- name: Install net-framework
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/net-framework/ndp48-x86-x64-allos-enu.exe'
    state: present
    arguments: /passive /norestart /log C:\logs\net-framework-4.8.log
