---
# Main file for 7zip
# Generally speaking this shouldn't be changed at all, it should just work!

- name: install 7zip
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/7zip/7z2401-x64.exe'
    state: present
    arguments: /S /D=D:\3rdparty\7Zip

- name: Ensure that 7zip is present on the global system path, and in the specified order
  win_path:
    elements:
    - 'D:\3rdparty\7zip'

- name: Remove old 7zip installation
  ansible.windows.win_file:
    path: 'C:\\Program Files\\7-Zip'
    state: absent
  ignore_errors: True
