---
# Main file for roles/windows/tortoise git 
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook
# This is because |basename or filters in general don't work with galaxy


- name: Install tortoise git 
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/tortoise-git/TortoiseGit-2.15.0.0-64bit.msi'
    state: present
    arguments: /qn /l*v "C:\logs\TortoiseGit-2.15.0.0-64bit.log" TARGETDIR="D:\3rdparty\Tortoise Git" INSTALLDIR="D:\3rdparty\Tortoise Git"
