---
# Main file for roles/windows/aspnetcore-runtime
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

# - name: Copy aspnetcore-runtime
#   win_copy:
#     src: '/opt/updates/aspnetcore-runtime-6.0.25-win-x64.exe'
#     dest: 'C:\\temp\\aspnetcore-runtime-6.0.25-win-x64.exe'

- name: Install aspnetcore-runtime
  win_package:
    path: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/dotnet-framework/aspnetcore-runtime-6.0.27-win-x64.exe'
    url_username: 'admin'
    url_password: 'MECO_Admin@2023'
    state: present
    arguments: /install /quiet /norestart /log C:\logs\aspnetcore-runtime-6.0.25-install.log