---
# Main file for roles/windows/Postman
# Generally speaking this shouldn't be changed, excepr for the 'application'. Replace it with the name of application defined in playbook

# - name: Copy Postman
#   win_copy:
#     src: '/opt/updates/Postman-win64-Setup.exe'
#     dest: 'C:\\temp\\Postman-win64-Setup.exe'

- name: Download Postman
  win_get_url:
    url: 'http://10.110.133.20:8082/artifactory/utilities-software/windows/postman/Postman-win64-Setup.exe'
    dest: 'C:\\temp\\Postman-win64-Setup.exe'

- name: Install Postman
  win_shell: 'C:\\temp\\Postman-win64-Setup.exe'
